# Generated by Django 4.1 on 2024-01-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoundationCalculationTask',
            fields=[
                ('calID', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('status', models.IntegerField(blank=True, choices=[(1, '计算中'), (2, '计算完成')], default=1, null=True, verbose_name='计算状态')),
                ('foundation_pit', models.JSONField(verbose_name='基坑计算参数')),
                ('result', models.JSONField(verbose_name='计算结果')),
            ],
        ),
    ]
