# Generated by Django 4.1 on 2023-06-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundationpit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundationcalculationtask',
            name='calID',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
